### ISSUE TITLE
[Story] Help users understand at a glance "dangerous" permission by app

### ISSUE THREAD

**Issue by megdeb** [covid19-apptracker/covid19-apptracker#144]
_User Story_
As a member of the public, I would like to visit the website, identify an app in my country and know if it's asking for information I should be concerned about.

_Impact_
Displaying per app, what google qualifies as "dangerous" permissions allows for deeper understanding of privacy issues related to the app.

_Background_ 
Every permission isn't equally concerning when it comes to privacy. Google lists specific permissions as "dangerous" meaning:

"Only dangerous permissions require user agreement. The way Android asks the user to grant dangerous permissions depends on the version of Android running on the user's device, and the system version targeted by your app." 

_Task Breakdown_
- [x] Define data model change #146 
- [x] Prototypes of UI #91 
- [x] ID database which perms are dangerous #131 
- [x] Display on frontend which perms are dangerous #132 
- [ ] Add more as needed

_Acceptance Criteria_
- [x] implement automated approach to displaying which permissions on detailed app page are the "dangerous" permissions

_Engineering Notes_
- Reference: #122 
https://developer.android.com/guide/topics/permissions/overview#dangerous-permission-prompt
- New data model documentation that includes "dangerous" permissions
- Prototypes of the UI should be reviewed by team (Aug-29)
