### ISSUE TITLE
Create and finalize Team Page

### ISSUE THREAD

**Issue by megdeb** [covid19-apptracker/covid19-apptracker#29]
- [x] Finalize copy - #28  @megdeb 

- [x] Design Team Page Layout https://github.com/family-hackathon/covid19-apptracker/issues/30 @JDBnhs 

- [x] Build Team Page in React https://github.com/family-hackathon/covid19-apptracker/issues/31 @JDBnhs 

- [x] Add Team Page to the Navbar and the Footer elements https://github.com/family-hackathon/covid19-apptracker/issues/55 @JDBnhs
