### ISSUE TITLE
[Story] Release code as open source

### ISSUE THREAD

**Issue by megdeb** [covid19-apptracker/covid19-apptracker#74]
_User Story_
As another software engineer, I would like to review and learn about how the project works by reviewing the code.

_Impact_
Open sourcing the code will allow for greater transparency around the project. This will also be more cost effective, as paying for a private repo is the "most expensive" part of the project right now. Once open source, we can also apply for a free jira license - https://www.atlassian.com/software/views/open-source-license-request. 

_Background_
Open source does not mean anyone can commit changes. Open source simply means the code is public and available for review. Types of open source projects can be licensed as follows: https://opensource.org/licenses/alphabetical

_Task Breakdown_
- [x] Security scans #103
- [x] Minimum refactoring necessary #105 #101 
- [x] Add open source license #136 
- [x] Change repo name #140 
- [x] Dependabot #117 
- [x] Dependabot #115 
- [x] Modify commit history #148 
- [x] Refactor components #105 
- [x] Add github icon on website #155 

_Acceptance Criteria_
- [x] back-end code is public
- [x] front-end code is public

_Engineering Notes_
- @carmayna, as discussed, can you please protect search criteria in a secrets manager

**Comment by megdeb** [comment]
I am pulling out website content mods and making its own story.
